# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Java CI with Maven

# Déclencheur : quand exécuter ce workflow ?
on:
  push:
    branches: [ "master" ] # S'exécute à chaque push sur la branche "master"

# Les tâches à effectuer
jobs:
  # On définit une tâche nommée "build"
  build:
    # La machine virtuelle sur laquelle exécuter la tâche
    runs-on: ubuntu-latest

    # La séquence d'étapes à suivre
    steps:
      # Étape 1 : Récupérer notre code depuis le dépôt GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer la bonne version de Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Étape 3 : Construire le projet avec Maven
      # C'est ici que la compilation et les tests (si on en avait) sont exécutés
      - name: Build with Maven
        run: mvn -B package --file pom.xml